repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.20.0 # Use the latest version
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
