name: Tests

on:
  push:
    branches:
      - testing

jobs:
  test:
    name: Test on ${{ matrix.os-python.os }} - Python ${{ matrix.os-python.python-version }}
    runs-on: ${{ matrix.os-python.os }}
    strategy:
      fail-fast: false
      matrix:
        os-python:
          - {os: ubuntu-latest, python-version: '3.10'}
          - {os: ubuntu-latest, python-version: '3.11'}
          - {os: ubuntu-latest, python-version: '3.12'}
          - {os: windows-latest, python-version: '3.12'}
          - {os: macos-latest, python-version: '3.12'}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.os-python.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.os-python.python-version }}
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
        shell: bash
      - name: Install pytest
        run: |
          pip install pytest
        shell: bash
      - name: Run tests
        run: |
          pytest tests/ -v --tb=short
        shell: bash
